---
- hosts: localhost
  remote_user: ubuntu
  tasks:
    - name: get docker version
      shell: "docker -v | cut -d ' ' -f 3 | cut -d ',' -f 1"
      register: version

    - debug: var=version.stdout

    - name: do something if version is 1.13.0
      shell: "echo it is 1.13.0"
      when: version.stdout == "1.13.0"

    - name: do nothing if version is 1.13.0
      shell: "echo nothing"
      when: version.stdout != "1.13.0"